### ISSUE TITLE
Output parsing for pass/fail

### ISSUE THREAD

**Issue by bwuerstle** [Florin-Popescu/vscode-unity-test-adapter#24]
If I understand correctly, the pass / fail is determined by parsing stdout stream.
When I run tests, the "TEST RESULTS" window displays that tests had passed, but the extension does not recognize this and displays that the tests failed.
Is there a format to follow for recognizing / parsing the stdout stream?

![test-result-fail](https://github.com/Florin-Popescu/vscode-unity-test-adapter/assets/25047412/1b85410b-c77e-4c5c-86b3-645c35ffea33)

**Comment by detrohutt** [comment]
@bwuerstle  I was able to workaround (may break other configurations for all I know) it by modifying the extension's code:
In `~/.vscode/extensions/fpopescu.vscode-unity-test-adapter-0.1.3/out/testRunner.js` I changed line 210 (the first line of `checkTestCaseResult()`) from
```
let testCaseRegex = new RegExp(node.id + '\\)' + this.testResultString);
```
to
```
let testCaseRegex = new RegExp(node.id + this.testResultString);
```

The code I removed was added over 4 months ago in [this commit](https://github.com/Florin-Popescu/vscode-unity-test-adapter/commit/d26ca7fe576433c0140d9800139a6519eeca1819) so my guess is maybe something changed with the output format of unity since then that causes it to no longer match that.
