### ISSUE TITLE
Activate the extension

### ISSUE THREAD

**Issue by BIKA-C** [Florin-Popescu/vscode-unity-test-adapter#4]
Hi, I am really excited found this extension that visualizes the unit test results.

I have the unit framework configured and working properly. If I just compile the unitTest.c, it will show the proper output.
But for this extension, how to configure it to make it work? I am a little confused by configuration terms.
I have tried the following:
```json
    "unityExplorer.testSourcePath": "test/unitTest.c",
    "unityExplorer.projectSourcePath": "test"
```
The Unit Test Explorer shows empty and the refreshing button keeps revolving. I appreciate that if a working example could be provided. I am using Windows.

**Comment by Florin-Popescu** [comment]
Hello! I have created this extension with my exact use case in mind, so I have not yet put much thought into how to make it as generally usable as possbile. That being said, all paths the extension expects in its settings are folders, not actual files, so I think that is where your issue is.

Let's take an example folder structure:
`.` - the root of the workspace
`./makefile` - the makefile which describes how to build the unit tests
`./src` - the folder where all tested sources are to be found
`./src/foo.c` - a testable source file
`bar()` - a function in `foo.c` which should be unit tested
`./test` - the folder where the unit test sources are to be found
`./test/fooTest.c `- a unit test for `foo.c`
`test_bar1()` and `test_bar2()` - actual unit tests: functions in `fooTest.c` which test `bar()` in `foo.c`
`./out/test` - the path to the built unit tests
`./out/test/fooTest.exe` - the executable which would be built by the extension to run the tests in `fooTest.c`

Following this example, the configuration might look like:
`"unityExplorer.makeCwdPath": "."` - this is where make will be run to build the unit tests
`"unityExplorer.projectSourcePath": "src"` - the path to the testable sources. On any change to files in this folder, the extension will look for tests which match the changed file and mark them as old so you know the tests need to be re-run. So if `foo.c` changes, `fooTest` will be old and need to rerun.
`"unityExplorer.sourceFileRegex": "\\w+\\.[ch]"` - a regular expression to match any file named *.c or *.h.
`"unityExplorer.testBuildPath": "out/test"` - the path to the unit test executables created by `make`. This is where the extension finds the test executables to run them.
`"unityExplorer.testBuildCommandArgs": ""` - additional arguments which should be passed to `make` when building a unit test. Might be `-DTEST` to add a `TEST` define which would be seen by the source files during compilation
`"unityExplorer.testCaseRegex": "void\\s+(test_.*)\\s*\\(.*\\)"` - the extension will look for functions which match the regex and treat them as unit tests, so in this case `void test_bar1(params...)` and `void test_bar2(params...)`
`"unityExplorer.testFileRegex": "\\w+Test.c"` - every file which matches the regex contains unit tests, so in this case `fooTest.c`
`"unityExplorer.testSourcePath": "test"` - the extension will only look in the `./test` folder for unit test files.
`"unityExplorer.prettyTestCaseRegex": "test_(\\w+)"` - the extension will display any test functions without the `test_` prefix, so instead of `test_bar1` and `test_bar2`, the tests will appear as `bar1` and `bar2`
`"unityExplorer.prettyTestFileRegex": "(\\w+)Test.c"` - the extension will display any test files without the `Test.c` suffix, so you would have `foo`

This should leave you with the test extension displaying:
\\/ :heavy_check_mark: foo
        :heavy_check_mark: bar1
        :heavy_check_mark: bar2

or without the 2 pretty settings:
\\/ :heavy_check_mark: fooTest.c
        :heavy_check_mark: test_bar1
        :heavy_check_mark: test_bar2

Now the limitations to the way the extension currently works are:
- calls `make [unityExplorer.testBuildPath]/unit_test.exe`, so a makefile is mandatory
- testable and uni test sources need to follow a similar naming convention
- built unit test files must have the same name as the unit test sources (so unitTest.c -> unitTest.exe)
- the extension attempts to build tests by using `make [unityExplorer.testBuildPath]/utest.exe` on Windows or `make [unityExplorer.testBuildPath]/utest` on Linux. The makefile must be able to build from the correct unit test sources based on this.

Please let me know if you succeed in configuring your extension.

Also, I would like to have this extension as generally usable as possible, so any improvements you can think of will be highly appreciated. Maybe this example should be added to the README.md?

**Comment by Florin-Popescu** [comment]
Assuming it's been resolved since there has been no reply for 2 weeks.
